baseURL: /
languageCode: en-us
theme: raditian-free-hugo-theme-data-science
params:
  footer:
    copyright: © Matt Dancho. All rights reserved.
    site_logo:
      _2x: img/general/business-science-logo.png
      alt: Design & Code - Business Science
      x: img/general/business-science-logo.png
  googleAnalyticsID: ''
  logo:
    text1: Sunil
    text2: Thapa
  plugins:
    css:
      - URL: css/main.css
      - URL: css/rad-icons.css
      - URL: css/custom.css
    js:
      - URL: js/rad-animations.js
      - URL: js/sticky-header.js
      - URL: js/library/fontfaceobserver.js
  sections:
    - showcase
    - about
    - client-and-work
    - experience
    - education
    - research
    - project
    - testimonial
    - contact
menu:
  footer:
    - URL: '#about'
      name: About
      weight: 2
    - URL: '#experience'
      name: Experience
      weight: 3
    - URL: '#education'
      name: Education
      weight: 4
    - URL: '#research'
      name: Research
      weight: 5
    # - URL: '#project'
    #   name: Project
    #   weight: 6
    - URL: '#testimonial'
      name: Testimonial
      weight: 7
    - URL: '#contact'
      name: Contact
      weight: 8
  header:
    - URL: '#about'
      name: About
      weight: 2
    - URL: '#experience'
      name: Experience
      weight: 3
    - URL: '#education'
      name: Education
      weight: 4
    - URL: '#research'
      name: Research
      weight: 5
    # - URL: '#project'
    #   name: Project
    #   weight: 6
    - URL: '#testimonial'
      name: Testimonial
      weight: 7
    - URL: '#contact'
      name: Contact
      weight: 8